let ZiWeiStarEnum = {
  ZIWEI: "紫微",
  TIANJI: "天机",
  TAIYANG: "太阳",
  WUQU: "武曲",
  TIANTONG: "天同",
  LIANZHEN: "廉贞",
};
let TianFuStarEnum = {
  TIANFU: "天府",
  TAIYIN: "太阴",
  TANLANG: "贪狼",
  JVMEN: "巨门",
  TIANLIANG: "天梁",
  TIANXIANG: "天相",
  QISHA: "七杀",
  POJUN: "破军",
};
let YearGanStarEnum = {
  QINGYANG: "擎羊",
  TUOLUO: "陀螺",
  TIANYUE: "天钺",
  TIANKUI: "天魁",
  LUCUN: "禄存",
  TIANFU: "天福",
  TIANGUAN: "天官",
  ZHENGKONG: "正空",
  FUKONG: "副空",
};
let HourStarEnum = {
  WENCHANG: "文昌",
  WENQU: "文曲",
  HUOXING: "火星",
  LINGXING: "铃星",
  DIJIE: "地劫",
  TIANKONG: "天空",
  TAIFU: "台辅",
  FENGGAO: "封诰",
};
arr = [
  {
    star: ZiWeiStarEnum.ZIWEI,
    light: [
      StarLightEnum.PING,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.WANG,
      StarLightEnum.DI,
    ],
  },
  {
    star: ZiWeiStarEnum.TIANJI,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.LI,
      StarLightEnum.PING,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.LI,
    ],
  },
  {
    star: ZiWeiStarEnum.TAIYANG,
    light: [
      StarLightEnum.XIAN,
      StarLightEnum.BU,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.DI,
      StarLightEnum.LI,
      StarLightEnum.PING,
      StarLightEnum.XIAN,
    ],
  },
  {
    star: ZiWeiStarEnum.WUQU,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.DI,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.DI,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: ZiWeiStarEnum.TIANTONG,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.BU,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.BU,
      StarLightEnum.WANG,
      StarLightEnum.PING,
      StarLightEnum.PING,
    ],
  },
  {
    star: ZiWeiStarEnum.LIANZHEN,
    light: [
      StarLightEnum.PING,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.LI,
      StarLightEnum.XIAN,
      StarLightEnum.PING,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.LI,
    ],
  },
  {
    star: TianFuStarEnum.TIANFU,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.DI,
      StarLightEnum.WANG,
      StarLightEnum.WANG,
    ],
  },
  {
    star: TianFuStarEnum.TAIYIN,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.BU,
      StarLightEnum.XIAN,
      StarLightEnum.XIAN,
      StarLightEnum.XIAN,
      StarLightEnum.XIAN,
      StarLightEnum.PING,
      StarLightEnum.LI,
      StarLightEnum.WANG,
      StarLightEnum.WANG,
    ],
  },
  {
    star: TianFuStarEnum.TANLANG,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.LI,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: TianFuStarEnum.JVMEN,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.BU,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
      StarLightEnum.PING,
      StarLightEnum.WANG,
      StarLightEnum.PING,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.PING,
    ],
  },
  {
    star: TianFuStarEnum.TIANXIANG,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.PING,
      StarLightEnum.DI,
      StarLightEnum.DI,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
    ],
  },
  {
    star: TianFuStarEnum.TIANLIANG,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: TianFuStarEnum.QISHA,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.PING,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: TianFuStarEnum.POJUN,
    light: [
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.XIAN,
      StarLightEnum.WANG,
      StarLightEnum.PING,
      StarLightEnum.MIAO,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.XIAN,
      StarLightEnum.WANG,
    ],
  },
  {
    star: HourStarEnum.HUOXING,
    light: [
      StarLightEnum.NONE,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.LI,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.LI,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: HourStarEnum.LINGXING,
    light: [
      StarLightEnum.NONE,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.LI,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.LI,
      StarLightEnum.XIAN,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: YearGanStarEnum.QINGYANG,
    light: [
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
      StarLightEnum.NONE,
      StarLightEnum.XIAN,
      StarLightEnum.MIAO,
      StarLightEnum.NONE,
      StarLightEnum.XIAN,
      StarLightEnum.MIAO,
      StarLightEnum.NONE,
      StarLightEnum.WANG,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: YearGanStarEnum.TUOLUO,
    light: [
      StarLightEnum.NONE,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.NONE,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.NONE,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.NONE,
      StarLightEnum.MIAO,
    ],
  },
  {
    star: HourStarEnum.WENCHANG,
    light: [
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.WANG,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
      StarLightEnum.LI,
      StarLightEnum.DI,
      StarLightEnum.MIAO,
      StarLightEnum.XIAN,
    ],
  },
];
